apiVersion: v1
kind: Pod
metadata:
  name: python-a
  labels: { app: python-a }
  annotations:
    io.podman.annotations.networks: consul-mesh
spec:
  restartPolicy: Always
  containers:
    # --- Your app image with app.py baked in ---
    - name: app
      image: registry.internal/apps/python-a:1.0
      # If your image already has CMD to run app.py, delete the next 2 lines:
      command: ["python"]
      args: ["/app/app.py"]
      ports:
        - containerPort: 8080
          hostPort: 8081
          protocol: TCP
      env:
        - { name: LISTEN_ADDR, value: "0.0.0.0:8080" }   # use in your app if needed

    # --- Envoy sidecar: local upstream 9191 -> service "python-b" ---
    - name: sidecar
      image: registry.internal/mesh/consul-envoy:1.0
      command: ["/init-consul-sidecar.sh"]
      env:
        - { name: CONSUL_HTTP_ADDR, value: "http://consul-client:8500" }
        - { name: CONSUL_GRPC_ADDR, value: "consul-client:8502" }
        # - { name: CONSUL_HTTP_TOKEN, value: "REDACTED_SERVICE_TOKEN" }
        - { name: SERVICE_NAME, value: "python-a" }
        - { name: SERVICE_PORT, value: "8080" }
        - { name: UPSTREAMS, value: "python-b:9191" }    # key bit
        - { name: ENVOY_ADMIN_BIND, value: "0.0.0.0:19000" }
      ports:
        - containerPort: 19000
          hostPort: 19001
          protocol: TCP
